export const shipments: Shipmnet[] = [
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 6000,
    status: "draft",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 7000,
    status: "completed",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 7500,
    status: "canceled",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 8000,
    status: "in-transit",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 5600,
    status: "completed",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 2900,
    status: "draft",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 6700,
    status: "draft",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 7000,
    status: "draft",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 7000,
    status: "draft",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 7000,
    status: "draft",
  },
  {
    date: new Date(),
    reciever: "Ramon Rasheed",
    destination: "Lagos, NG",
    shipmentId: "F65454546545",
    source: "DHL",
    sourceSvgUrl: ".///",
    price: 7000,
    status: "draft",
  },
];

export const transactions: Transaction[] = [
  {
    date: new Date(),
    description: "New Money In",
    type: "inflow",
    amount: 5000,
    reference: "F5465477655",
  },
  {
    date: new Date(),
    description: "New Money Out",
    type: "outflow",
    amount: 5000,
    reference: "F546G477655",
  },
  {
    date: new Date(),
    description: "New Money In",
    type: "inflow",
    amount: 5000,
    reference: "F5465477655",
  },
  {
    date: new Date(),
    description: "New Money Out",
    type: "outflow",
    amount: 5000,
    reference: "F546G477655",
  },
  {
    date: new Date(),
    description: "New Money In",
    type: "inflow",
    amount: 5000,
    reference: "F5465477655",
  },
  {
    date: new Date(),
    description: "New Money Out",
    type: "outflow",
    amount: 5000,
    reference: "F546G477655",
  },
  {
    date: new Date(),
    description: "New Money In",
    type: "inflow",
    amount: 5000,
    reference: "F5465477655",
  },
  {
    date: new Date(),
    description: "New Money Out",
    type: "outflow",
    amount: 5000,
    reference: "F546G477655",
  },
  {
    date: new Date(),
    description: "New Money In",
    type: "inflow",
    amount: 5000,
    reference: "F5465477655",
  },
  {
    date: new Date(),
    description: "New Money Out",
    type: "outflow",
    amount: 5000,
    reference: "F546G477655",
  },
];

export const addresses: Address[] = [
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
  {
    date: new Date(),
    name: "John Doe",
    phoneNumber: "0123456789",
    email: "johndoe@email.com",
    location: "House 8, Ayobami Comm...",
  },
];
